/**
 * Expanded class-path quest pools — 5 actionable quests per tier.
 * Key: `${seal}:${routeId}` → [tier1[], tier2[], tier3[]]
 * Used by dailies + SkillTree so both stay in sync.
 */
export const ROUTE_QUEST_POOLS = {
  '1:leadership': [
    [
      'Show up on time to one commitment and stay fully present for the whole thing.',
      'Speak first in a meeting or group once today — state a clear preference.',
      'Hold eye contact and finish one request without hedging or apologizing.',
      'Decide for the group when someone stalls — name the next step out loud.',
      'Own one mistake publicly in under two sentences, then move forward.',
    ],
    [
      'Set a clear goal for a shared project and say it out loud to everyone involved.',
      'Assign one task with a deadline and follow up once before it is due.',
      'Choose a direction when the group stalls — then own the outcome.',
      'Run a 15-minute standup or check-in that ends with named owners.',
      'Give one piece of direct feedback that raises the standard, not the temperature.',
    ],
    [
      'Lead a session or project from kickoff to handoff without disappearing mid-way.',
      'Give feedback that raises the standard for the whole team, not just one person.',
      'Recruit or nominate someone else into a stretch responsibility and back them.',
      'Facilitate a hard conversation to a decision — leave with a written next step.',
      'Ship a visible win this week that others can point to as your lead.',
    ],
  ],
  '1:entrepreneurship': [
    [
      'Write down one problem you personally want solved this month — one sentence only.',
      'Talk to three people about that problem and note the same phrase they repeat.',
      'Sketch a one-page offer or product idea you could test within seven days.',
      'List your unfair advantages (skills, access, audience) in ten bullets or fewer.',
      'Price a rough offer on paper even if you are not ready to sell it yet.',
    ],
    [
      'Ship a minimum version to one real person and collect written feedback.',
      'Ask for payment or a clear yes/no on your offer — no soft “maybe” endings.',
      'Run the same offer three times and change only one variable each round.',
      'Cut one feature from your MVP that you love but customers have not asked for.',
      'Block two hours for deep build work with notifications off — protect it.',
    ],
    [
      'Document a repeatable process so someone else could run the offer without you.',
      'Set a weekly revenue or impact target and track it for four consecutive weeks.',
      'Hand off or automate one part of the work you no longer need to do alone.',
      'Publish a simple case study from a real customer or early user.',
      'Decide your next hire, contractor, or tool — and take one concrete step toward it.',
    ],
  ],
  '1:physical': [
    [
      'Move your body for 20 straight minutes today — walk, stretch, or train.',
      'Choose one physical standard (sleep, steps, water) and hit it before midnight.',
      'Do a warm-up before your hardest task of the day — treat the body as gear.',
      'Stand or walk during one call you would normally take sitting.',
      'Put your phone in another room for one focused physical session.',
    ],
    [
      'Complete three training sessions this week and log them somewhere visible.',
      'Increase one measurable (reps, distance, hold time) by a small honest margin.',
      'Recover on purpose: stretch, sleep, or mobility work after a hard day.',
      'Fuel one workout with a real meal plan — no improvising after the fact.',
      'Invite one person to train with you and keep the appointment.',
    ],
    [
      'Complete a physical challenge you would have called “not yet” thirty days ago.',
      'Lead someone else through a workout or movement practice you know well.',
      'Build a four-week training plan and finish week one without skipping.',
      'Test a personal record and write down what the attempt taught you.',
      'Protect recovery as hard as training — schedule it like a meeting.',
    ],
  ],
  '2:relationships': [
    [
      'Send one honest check-in to someone you have been meaning to reach.',
      'Listen for five minutes without planning your reply — then reflect one sentence.',
      'Name one need out loud in a relationship instead of hinting.',
      'Repair a small friction today with a clear apology or clarification.',
      'Put a recurring hangout or call on the calendar with someone who matters.',
    ],
    [
      'Have one conversation where you ask three curious questions before advising.',
      'Share a vulnerable truth with someone safe — keep it specific, not dramatic.',
      'Negotiate one boundary kindly and keep it for the rest of the week.',
      'Do a favor that costs time, not money, for someone in your inner circle.',
      'Celebrate someone’s win without redirecting the story back to you.',
    ],
    [
      'Host or plan a gathering that strengthens a real bond, not a network flex.',
      'Resolve one recurring conflict with a written agreement both can see.',
      'Introduce two people who should know each other and follow up once.',
      'Commit to a relationship ritual (weekly call, walk, meal) for a full month.',
      'Ask for deeper partnership on something important — and accept the answer.',
    ],
  ],
  '2:empathy': [
    [
      'Name the feeling under your reaction today before you act on it.',
      'Mirror someone’s emotion back to them accurately once in conversation.',
      'Sit with discomfort for two minutes without numbing (scroll, snack, exit).',
      'Write three lines about how a hard situation feels from the other side.',
      'Offer presence, not advice, to one person who is struggling.',
    ],
    [
      'Ask “what do you need?” and wait — then do only what they actually ask.',
      'Catch yourself projecting once today and correct it out loud or in writing.',
      'Validate someone’s experience without agreeing with every conclusion.',
      'Take a break when flooded — return to the conversation after you regulate.',
      'Notice one body cue (tight jaw, shallow breath) and reset before responding.',
    ],
    [
      'Hold space for a hard story without making yourself the hero of it.',
      'Help two people understand each other in a conflict — stay neutral.',
      'Practice compassionate honesty: kind and clear in the same sentence.',
      'Create a calm container (walk, tea, quiet room) for someone who needs it.',
      'Teach one regulation tool you use to a friend who asked for help.',
    ],
  ],
  '2:social': [
    [
      'Learn and use one new person’s name correctly in a group setting.',
      'Make one warm introduction between two people in the same room.',
      'Ask a group question that draws quieter voices in.',
      'Leave one gathering having thanked the host specifically for something real.',
      'Follow up with one new contact within 24 hours with a useful note.',
    ],
    [
      'Host a small hangout (3–6 people) with a simple purpose and clear invite.',
      'Read a room once today and adjust your volume, topic, or pace.',
      'Include someone on the edge of a circle without making it awkward.',
      'Share credit publicly for someone else’s contribution in a group.',
      'Exit a conversation cleanly — no ghosting mid-thread.',
    ],
    [
      'Facilitate a group to a decision and capture it where everyone can see.',
      'Build a recurring social ritual (monthly dinner, club, call) and run it twice.',
      'Mediate a mild social conflict so both people feel heard.',
      'Curate a guest list for impact, not status — then follow through.',
      'Leave a community better than you found it: one process, doc, or welcome.',
    ],
  ],
  '3:voice': [
    [
      'Say one true sentence today you almost softened into nothing.',
      'Record a 60-second voice note explaining an idea clearly — no script polish.',
      'Speak up once in a room where you usually stay quiet.',
      'Practice your opener aloud three times before an important conversation.',
      'Cut filler (“just”, “maybe”, “I think”) from one request and send it clean.',
    ],
    [
      'Present an idea for three minutes to a real audience (even one person).',
      'Tell a short story with a beginning, turn, and point — then stop.',
      'Ask for the floor once and hold it without rushing or apologizing.',
      'Deliver feedback live instead of hiding it in text.',
      'Lead a toast, update, or briefing that ends on a clear ask.',
    ],
    [
      'Influence a decision with a spoken argument — measure by the outcome, not applause.',
      'Teach or brief a group for 10+ minutes without reading slides word-for-word.',
      'Handle a tough question live without collapsing or attacking.',
      'Record or speak a piece meant to persuade and get one critique.',
      'Use your voice to open a door for someone else in public.',
    ],
  ],
  '3:creation': [
    [
      'Make something small today and finish it — ugly is allowed, abandoned is not.',
      'Block 45 minutes for creation with no consumption (no feeds, no “research”).',
      'Start a piece you have been circling; get past the blank first page.',
      'Limit the palette: one medium, one constraint, one session.',
      'Show a rough to nobody — keep it private to protect early momentum.',
    ],
    [
      'Develop a recognizable style choice and repeat it across three pieces.',
      'Revise yesterday’s work for thirty focused minutes — no new starts.',
      'Ask for critique from one person who will be honest, not polite.',
      'Ship a draft into the world (post, send, pin, print) before you feel ready.',
      'Kill one darling — remove something you love that weakens the piece.',
    ],
    [
      'Complete a body of work (3+ related pieces) and present it as a set.',
      'Create something that means more than decoration — state the meaning in one line.',
      'Collaborate once without losing your voice in the blend.',
      'Archive or exhibit the work so it exists outside your hard drive.',
      'Start the next series only after naming what this one taught you.',
    ],
  ],
  '3:writing': [
    [
      'Write 300 honest words today — publish optional, finish required.',
      'Cut 20% from a paragraph without losing the point.',
      'Describe one scene with sensory detail; no abstractions allowed.',
      'Journal one page about a decision you are avoiding.',
      'Rewrite a messy email until it is three sentences and clear.',
    ],
    [
      'Draft a short story, essay, or thread with a real arc (setup → turn → landing).',
      'Edit for voice: read aloud and fix every clunky line.',
      'Send writing to one reader and ask one specific question.',
      'Write on a schedule three days this week — same time if possible.',
      'Turn notes into a clean outline before drafting the hard section.',
    ],
    [
      'Publish or submit a finished piece (post, pitch, newsletter, zine).',
      'Build a simple writing system (folders, titles, revision passes) and use it.',
      'Write something that teaches — clarity over cleverness.',
      'Complete a multi-day writing project and ship the final file.',
      'Mentor someone’s draft with margin notes that make it sharper.',
    ],
  ],
  '4:discipline': [
    [
      'Keep one non-negotiable routine today (wake, move, or deep work block).',
      'Make your bed or clear your desk before opening messages.',
      'Do the hardest item on your list before 11am.',
      'Track one habit with a visible checkmark — no app required.',
      'End the day by writing tomorrow’s top three — then stop working.',
    ],
    [
      'Hit the same routine five days in a row and log the streak.',
      'Remove one friction (prep clothes, block site, pack bag) the night before.',
      'Keep a promise to yourself that nobody else is watching.',
      'Work a focused 50/10 split for two hours without multitasking.',
      'Say no once to protect a discipline you already committed to.',
    ],
    [
      'Run a 21-day streak on one discipline and review what broke the near-misses.',
      'Systemize the routine so it survives low motivation days.',
      'Teach your discipline method to someone else in writing.',
      'Raise the standard: same habit, stricter definition of “done.”',
      'Audit your week and cut one commitment that sabotages consistency.',
    ],
  ],
  '4:organization': [
    [
      'Inbox or desktop to zero once today — archive, delete, or schedule.',
      'Put every open loop on one list; close or date three of them.',
      'Label or file five things that have been “temporary” for weeks.',
      'Plan tomorrow in ten minutes with time blocks, not wishes.',
      'Throw away or donate one pile of clutter you keep rediscovering.',
    ],
    [
      'Build a weekly review ritual and actually run it this week.',
      'Create a simple naming/filing convention and migrate ten items into it.',
      'Batch similar tasks (emails, errands, admin) into one block.',
      'Decline or defer one ask that does not fit the plan.',
      'Map a project on one page: goal, steps, owners, deadline.',
    ],
    [
      'Design a system others can use (shared board, checklist, calendar).',
      'Optimize one bottleneck — measure before/after in plain numbers.',
      'Run a planning session that ends with fewer projects, not more.',
      'Automate or template one recurring admin task.',
      'Leave a space (room, drive, calendar) sustainably orderly for seven days.',
    ],
  ],
  '4:systems': [
    [
      'Write the steps of one process you always reinvent — then follow it once.',
      'Find one repeated mistake and add a checklist item that prevents it.',
      'Time a recurring task; note where minutes leak.',
      'Replace a mental reminder with a calendar or board card.',
      'Document inputs → actions → outputs for something you own.',
    ],
    [
      'Automate one boring step (template, filter, shortcut, script).',
      'Build a dashboard or scoreboard for a metric you care about.',
      'Reduce a five-step process to three without losing quality.',
      'Create a failure mode note: “If X breaks, do Y.”',
      'Hand a teammate a process doc and watch where they get stuck.',
    ],
    [
      'Architect a system that runs weekly without you babysitting it.',
      'Connect two tools or teams so handoffs stop dropping.',
      'Review system metrics and change one rule based on evidence.',
      'Write an ops guide a stranger could follow in under an hour.',
      'Retire a broken process publicly — replace it the same day.',
    ],
  ],
  '5:exploration': [
    [
      'Try one unfamiliar route, tool, or neighborhood today on purpose.',
      'Ask a question you do not already know the answer to — then research for 20 minutes.',
      'Say yes to a small novelty that does not break your sleep.',
      'Collect three interesting inputs (article, walk, conversation) and note one insight.',
      'Break a tiny routine deliberately and observe what changes.',
    ],
    [
      'Run a one-week experiment with a clear hypothesis and success metric.',
      'Visit a place, scene, or community you have never entered.',
      'Learn a beginner skill for three sessions — stay a beginner willingly.',
      'Talk to someone outside your usual circle about how they solve a problem.',
      'Change your default entertainment for 48 hours; notice the craving.',
    ],
    [
      'Ship an exploration report: what you tried, what surprised you, what you keep.',
      'Turn curiosity into a mapped project with a next expedition date.',
      'Mentor someone’s first experiment without taking over.',
      'Choose a frontier (topic, place, craft) and commit ninety days of return visits.',
      'Drop an exploration that stopped teaching you — name why.',
    ],
  ],
  '5:adventure': [
    [
      'Do one thing today that raises your heart rate and requires courage.',
      'Leave the house for an unplanned hour with only a loose direction.',
      'Book or schedule a mini-adventure within the next fourteen days.',
      'Practice a safety skill (first aid note, route plan, buddy check).',
      'Tell one person your adventure intention so it becomes real.',
    ],
    [
      'Complete a challenge with weather, distance, or difficulty above comfort.',
      'Pack light and go — remove two “just in case” items.',
      'Navigate without autopilot for part of a trip (map, trail, transit).',
      'Invite a companion and lead the plan end-to-end.',
      'Write a field note after: what went wrong and what you loved.',
    ],
    [
      'Finish an expedition you trained for — document the arc.',
      'Lead others on an adventure you have already survived once.',
      'Plan a bigger trip with budget, dates, and a go/no-go checklist.',
      'Teach one outdoor or adventure skill to a beginner safely.',
      'Turn the story into something shared (photos, post, dinner tale).',
    ],
  ],
  '5:innovation': [
    [
      'Question one “that’s how we do it” rule and propose an alternative on paper.',
      'Steal like an artist: combine two unrelated ideas into a sketch.',
      'Prototype the dumbest version of an idea in under an hour.',
      'Ask “what if we couldn’t use X?” and list three workarounds.',
      'Collect five annoying friction points in a day — pick one to attack.',
    ],
    [
      'Run an A/B on a small decision and keep the winner.',
      'Build a demo that proves the concept to a skeptic.',
      'Kill your favorite idea if the evidence is weak — write the eulogy.',
      'Borrow a pattern from another industry and apply it once.',
      'Invite critique from someone who will try to break your prototype.',
    ],
    [
      'Ship an innovation into real use — not a slide, a change.',
      'Measure impact for a week and report honestly.',
      'Scale or productize the winning experiment.',
      'Teach the method (how you innovated) not just the artifact.',
      'Start the next invention only after retiring one failed bet cleanly.',
    ],
  ],
  '6:care': [
    [
      'Do one concrete care act today (meal, errand, listen, repair) without announcing it.',
      'Ask someone how they are — and stay for the real answer.',
      'Care for your own body first: water, food, or rest before hero mode.',
      'Send a specific appreciation text that names what they did.',
      'Fix one small comfort in a shared space (lightbulb, dish, blanket).',
    ],
    [
      'Show up for someone on a hard day with time, not just emoji.',
      'Cook or prepare nourishment for someone (including yourself) with intention.',
      'Keep a care promise you made — no silent downgrades.',
      'Notice over-giving once and renegotiate before resentment blooms.',
      'Create a calm hour for someone who never gets one.',
    ],
    [
      'Steward a person or space for a full week of reliable care.',
      'Build a care system (meal train, check-in cadence, chore board) that outlasts mood.',
      'Advocate for someone’s needs in a room where they are unheard.',
      'Teach care skills (listening, boundaries, practical help) to one person.',
      'Rest without guilt after a heavy care stretch — schedule it.',
    ],
  ],
  '6:family': [
    [
      'Initiate one warm contact with family (blood or chosen) today.',
      'Share a memory or photo that strengthens belonging.',
      'Do a household task someone else usually carries.',
      'Ask an elder or kid a real question and listen fully.',
      'Put a family ritual on the calendar (meal, call, game night).',
    ],
    [
      'Host or organize a family touchpoint and handle the logistics.',
      'Address one simmering family tension with calm clarity.',
      'Preserve a story — write or record it before it fades.',
      'Support a family member’s goal with a concrete assist this week.',
      'Keep a boundary that protects the family’s peace, not just your comfort.',
    ],
    [
      'Build or renew a family tradition and run it at least once.',
      'Be the kinkeeper: update the group, remember dates, connect the quiet ones.',
      'Mediate toward repair without forcing false harmony.',
      'Create a shared resource (album, calendar, fund, document) the family owns.',
      'Plan for the long arc — wills talk, care plan, or legacy project — one step.',
    ],
  ],
  '6:service': [
    [
      'Help once today without being asked and without collecting credit.',
      'Volunteer an hour to a need you did not create.',
      'Do the unglamorous task in a group setting.',
      'Offer a skill you have to someone who lacks it — twenty minutes.',
      'Leave a public space better than you found it.',
    ],
    [
      'Commit to a recurring service slot and keep it this week.',
      'Serve in a way that matches real need, not your preferred hero story.',
      'Train once so your help is safer and more useful next time.',
      'Recruit one helper instead of doing everything alone.',
      'Thank the invisible labor around you — name it specifically.',
    ],
    [
      'Lead a service effort from plan to cleanup.',
      'Build a service habit that survives busy seasons.',
      'Empower someone else to serve — hand them the lead.',
      'Measure impact: who is better off because you showed up?',
      'Rest and refill so service does not become self-erasure.',
    ],
  ],
  '7:contemplation': [
    [
      'Sit in silence for ten minutes — no phone, no optimizing the silence.',
      'Write three honest pages or a voice note about what is actually true today.',
      'Take a walk without podcasts; note three observations.',
      'Ask one deep question in a journal and refuse to answer it for 24 hours.',
      'End the day with a short review: what mattered, what was noise.',
    ],
    [
      'Keep a contemplation streak: five days of the same quiet practice.',
      'Read a dense page slowly and summarize it in your own words.',
      'Notice a recurring thought pattern and name it without fixing it yet.',
      'Choose solitude over a low-value social yes once this week.',
      'Meditate, pray, or reflect with a timer — stay until it ends.',
    ],
    [
      'Produce an insight artifact (essay, diagram, teaching) from direct looking.',
      'Hold a weekly contemplation block on the calendar for a month.',
      'Share one hard-won insight without performing certainty.',
      'Guide someone else into a short contemplative practice.',
      'Let an insight change one behavior this week — proof it landed.',
    ],
  ],
  '7:research': [
    [
      'Pick a question and find three credible sources before forming an opinion.',
      'Take structured notes (claim / evidence / open question) for thirty minutes.',
      'Challenge one belief with a source that disagrees — steelman it.',
      'Define terms before debating: write the definition you are using.',
      'Clear your browser of tab hoarding — save or drop each one.',
    ],
    [
      'Build a short lit review or brief on one topic (one page max).',
      'Interview someone with first-hand knowledge; ask follow-ups.',
      'Reproduce a result or example yourself instead of trusting the summary.',
      'Cite sources cleanly in something you share.',
      'Kill a cherished theory when the data does not support it.',
    ],
    [
      'Publish or present research others can verify.',
      'Maintain a personal knowledge base with searchable notes for ninety days.',
      'Mentor a beginner through their first research pass.',
      'Update an older conclusion publicly when you learn better.',
      'Turn research into a decision — ship the call, not just the folder.',
    ],
  ],
  '7:consciousness': [
    [
      'Catch one automatic reaction and insert a breath before you respond.',
      'Label an emotion precisely (not “bad” — specific word) three times today.',
      'Do a body scan once — tension map from jaw to feet.',
      'Notice when you are performing versus being — write one example.',
      'Track a trigger without acting on it for one full cycle.',
    ],
    [
      'Keep a pattern log for five days: trigger → story → urge → choice.',
      'Practice a regulation tool (box breath, walk, cold water) when activated.',
      'Ask “whose voice is this?” when self-talk turns harsh.',
      'Share one pattern insight with a trusted person.',
      'Change one micro-habit that feeds an unconscious loop.',
    ],
    [
      'Integrate: change a relationship or schedule based on what you learned.',
      'Teach a consciousness tool without spiritual theater.',
      'Hold paradox for a week — two true things, no forced merge.',
      'Design an environment that makes the awake choice easier.',
      'Review a year of patterns and write the next chapter’s rule.',
    ],
  ],
  '8:achievement': [
    [
      'Define today’s win in one measurable sentence — then hit it.',
      'Clear a blocker that has sat for more than three days.',
      'Ship something imperfect that moves a scoreboard.',
      'Publicly state a weekly target to someone who will ask later.',
      'Review yesterday’s results without drama — keep / stop / start.',
    ],
    [
      'Hit a stretch target you set in writing at the start of the week.',
      'Break a big goal into milestones and finish the next one.',
      'Compete cleanly — raise your output without tearing others down.',
      'Ask for a scoreboard (metrics, review, ranking) and face it.',
      'Recover fast after a miss: same-day corrective action.',
    ],
    [
      'Close a major goal and document how it was won.',
      'Raise the bar for your team or craft with a new standard.',
      'Win in public: present results, not intentions.',
      'Coach someone else to a measurable achievement.',
      'Pick the next mountain only after celebrating this one properly.',
    ],
  ],
  '8:wealth': [
    [
      'Track every expense today — no judgment, just data.',
      'Move money toward a named goal (even a small transfer).',
      'Read one statement you usually ignore; highlight one anomaly.',
      'Price your time for one hour of work — write the number down.',
      'Cut or pause one subscription that does not earn its keep.',
    ],
    [
      'Build a simple budget or forecast for the next thirty days.',
      'Negotiate once (rate, rent, fee, scope) with preparation notes.',
      'Create or improve one income asset (offer, content, skill product).',
      'Automate a savings or investment move.',
      'Have an honest money conversation with a partner or mentor.',
    ],
    [
      'Hit a net-worth or runway milestone you defined in advance.',
      'Build a wealth system (accounts, rules, reviews) that runs monthly.',
      'Teach someone a money skill you had to learn the hard way.',
      'Deploy capital or time into an asset with a written thesis.',
      'Review wealth goals against values — cut one that is just status.',
    ],
  ],
  '8:command': [
    [
      'Give one clear order or request with owner, deadline, and definition of done.',
      'Take responsibility for an outcome you could have blamed on someone else.',
      'Make a decision with incomplete information and own it.',
      'Stand in front of a group and set the frame for the next hour.',
      'Correct a standard violation kindly and immediately.',
    ],
    [
      'Run an operation (event, launch, shift) with a written plan and debrief.',
      'Delegate outcomes, not tasks — check results, not vibes.',
      'Hold someone accountable without humiliation.',
      'Protect the mission: say no to a distraction with a reason.',
      'After-action review: three keeps, three fixes, one owner each.',
    ],
    [
      'Command through a crisis or crunch without losing the plot.',
      'Build a chain of command or RACI so work does not need you every minute.',
      'Promote or elevate someone based on merit you can name.',
      'Carry the burden of an unpopular but correct call.',
      'Leave the unit stronger — docs, people, and standards upgraded.',
    ],
  ],
  '9:contribution': [
    [
      'Give something useful today with no invoice and no audience.',
      'Donate time, skill, or resources to a cause you actually respect.',
      'Finish one open loop that helps a group, not just you.',
      'Share knowledge in public that saves someone else an hour.',
      'Ask who needs help — then help the answer, not the fantasy.',
    ],
    [
      'Commit to a contribution project for two weeks minimum.',
      'Measure who benefited — names, not abstractions.',
      'Collaborate on impact; share credit aggressively.',
      'Remove a barrier for someone with less access than you.',
      'Give feedback that improves the commons (docs, process, product).',
    ],
    [
      'Complete a contribution cycle and close it with gratitude.',
      'Build a gift that keeps giving (template, tool, fund, curriculum).',
      'Mentor a contributor so the work outlives your availability.',
      'Release a project, role, or ego attachment that is done.',
      'Choose the next contribution based on need, not identity.',
    ],
  ],
  '9:teaching': [
    [
      'Explain one idea so a beginner could use it immediately.',
      'Teach for ten minutes — live or recorded — then ask what was unclear.',
      'Write a checklist someone else can follow without you.',
      'Correct a misunderstanding patiently without scoring points.',
      'Learn something new specifically so you can teach it better.',
    ],
    [
      'Run the same lesson twice; improve it from feedback between runs.',
      'Build a mini curriculum with three sessions and a practice task.',
      'Adapt your teaching to one learner’s pace and style.',
      'Assess learning with a demo, not a nod — watch them do it.',
      'Invite questions you cannot answer yet; research and return.',
    ],
    [
      'Mentor across multiple sessions until they hit a real goal.',
      'Hand the teaching role to your student for one full segment.',
      'Publish a durable lesson (guide, video, workshop) others can reuse.',
      'Create assessment that is fair, clear, and kind.',
      'Retire outdated teaching — update materials when truth moved on.',
    ],
  ],
  '9:creation': [
    [
      'Start a durable project that should still matter in a year — first brick today.',
      'Ship a rough version this week; imperfect is the point.',
      'Spend focused hours building without announcing it first.',
      'Choose materials or tools you will still respect in twelve months.',
      'Define “done enough to exist” and hit that bar today.',
    ],
    [
      'Show the work to three people and take notes on reactions, not ego.',
      'Publish or gift a finished piece into the world.',
      'Invite collaboration on the next version without losing the spine.',
      'Improve craft on purpose: one technique drill this week.',
      'Document the build so future-you can continue cold.',
    ],
    [
      'Leave something behind: finish a piece meant to outlast the moment.',
      'Archive, gift, or install the work where others can find it.',
      'Teach the making process once.',
      'Begin the legacy set — related works that form a body.',
      'Release attachment to praise; judge by the artifact’s honesty.',
    ],
  ],
}

/** Resolve quests for a route tier — expanded pool wins over inline fallback. */
export function resolveRouteStageQuests(number, routeId, stageIdx, fallbackQuests = []) {
  const key = `${Number(number)}:${routeId}`
  const pool = ROUTE_QUEST_POOLS[key]?.[stageIdx]
  if (Array.isArray(pool) && pool.length) return pool
  return Array.isArray(fallbackQuests) ? fallbackQuests : []
}
